/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsCreateRouteImport } from './routes/agents/create'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AgentsAgentIdSettingsRouteImport } from './routes/agents/$agentId.settings'
import { Route as AgentsAgentIdChatRouteImport } from './routes/agents/$agentId.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsCreateRoute = AgentsCreateRouteImport.update({
  id: '/agents/create',
  path: '/agents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdSettingsRoute = AgentsAgentIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdChatRoute = AgentsAgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/create': typeof AgentsCreateRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/create': typeof AgentsCreateRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/create': typeof AgentsCreateRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/create'
    | '/agents/'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/create'
    | '/agents'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/settings'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/create'
    | '/agents/'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AgentsCreateRoute: typeof AgentsCreateRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/create': {
      id: '/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AgentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/settings': {
      id: '/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/agents/$agentId/settings'
      preLoaderRoute: typeof AgentsAgentIdSettingsRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/chat': {
      id: '/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AgentsAgentIdChatRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdChatRoute: typeof AgentsAgentIdChatRoute
  AgentsAgentIdSettingsRoute: typeof AgentsAgentIdSettingsRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdChatRoute: AgentsAgentIdChatRoute,
  AgentsAgentIdSettingsRoute: AgentsAgentIdSettingsRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AgentsCreateRoute: AgentsCreateRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
