/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as PlaygroundStarredRouteImport } from './routes/playground/starred'
import { Route as PlaygroundSettingsRouteImport } from './routes/playground/settings'
import { Route as PlaygroundHistoryRouteImport } from './routes/playground/history'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundStarredRoute = PlaygroundStarredRouteImport.update({
  id: '/playground/starred',
  path: '/playground/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundSettingsRoute = PlaygroundSettingsRouteImport.update({
  id: '/playground/settings',
  path: '/playground/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundHistoryRoute = PlaygroundHistoryRouteImport.update({
  id: '/playground/history',
  path: '/playground/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/settings': typeof PlaygroundSettingsRoute
  '/playground/starred': typeof PlaygroundStarredRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/settings': typeof PlaygroundSettingsRoute
  '/playground/starred': typeof PlaygroundStarredRoute
  '/playground': typeof PlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/settings': typeof PlaygroundSettingsRoute
  '/playground/starred': typeof PlaygroundStarredRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/models'
    | '/settings'
    | '/playground/history'
    | '/playground/settings'
    | '/playground/starred'
    | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/models'
    | '/settings'
    | '/playground/history'
    | '/playground/settings'
    | '/playground/starred'
    | '/playground'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/models'
    | '/settings'
    | '/playground/history'
    | '/playground/settings'
    | '/playground/starred'
    | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  PlaygroundHistoryRoute: typeof PlaygroundHistoryRoute
  PlaygroundSettingsRoute: typeof PlaygroundSettingsRoute
  PlaygroundStarredRoute: typeof PlaygroundStarredRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/starred': {
      id: '/playground/starred'
      path: '/playground/starred'
      fullPath: '/playground/starred'
      preLoaderRoute: typeof PlaygroundStarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/settings': {
      id: '/playground/settings'
      path: '/playground/settings'
      fullPath: '/playground/settings'
      preLoaderRoute: typeof PlaygroundSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/history': {
      id: '/playground/history'
      path: '/playground/history'
      fullPath: '/playground/history'
      preLoaderRoute: typeof PlaygroundHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  PlaygroundHistoryRoute: PlaygroundHistoryRoute,
  PlaygroundSettingsRoute: PlaygroundSettingsRoute,
  PlaygroundStarredRoute: PlaygroundStarredRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
