/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SkillsCreateRouteImport } from './routes/skills.create'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as AgentsAgentIdVoiceRouteImport } from './routes/agents/$agentId.voice'
import { Route as AgentsAgentIdToolsRouteImport } from './routes/agents/$agentId.tools'
import { Route as AgentsAgentIdSettingsRouteImport } from './routes/agents/$agentId.settings'
import { Route as AgentsAgentIdMemoryRouteImport } from './routes/agents/$agentId.memory'
import { Route as AgentsAgentIdDashboardRouteImport } from './routes/agents/$agentId.dashboard'
import { Route as AgentsAgentIdChatRouteImport } from './routes/agents/$agentId.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsCreateRoute = SkillsCreateRouteImport.update({
  id: '/skills/create',
  path: '/skills/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdVoiceRoute = AgentsAgentIdVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdToolsRoute = AgentsAgentIdToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdSettingsRoute = AgentsAgentIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdMemoryRoute = AgentsAgentIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdDashboardRoute = AgentsAgentIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdChatRoute = AgentsAgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/skills/create': typeof SkillsCreateRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId/memory': typeof AgentsAgentIdMemoryRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId/tools': typeof AgentsAgentIdToolsRoute
  '/agents/$agentId/voice': typeof AgentsAgentIdVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/skills/create': typeof SkillsCreateRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId/memory': typeof AgentsAgentIdMemoryRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId/tools': typeof AgentsAgentIdToolsRoute
  '/agents/$agentId/voice': typeof AgentsAgentIdVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/skills/create': typeof SkillsCreateRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/agents/$agentId/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId/memory': typeof AgentsAgentIdMemoryRoute
  '/agents/$agentId/settings': typeof AgentsAgentIdSettingsRoute
  '/agents/$agentId/tools': typeof AgentsAgentIdToolsRoute
  '/agents/$agentId/voice': typeof AgentsAgentIdVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/files'
    | '/settings'
    | '/agents/$agentId'
    | '/skills/create'
    | '/agents/'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/dashboard'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/tools'
    | '/agents/$agentId/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/files'
    | '/settings'
    | '/agents/$agentId'
    | '/skills/create'
    | '/agents'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/dashboard'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/tools'
    | '/agents/$agentId/voice'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/files'
    | '/settings'
    | '/agents/$agentId'
    | '/skills/create'
    | '/agents/'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/dashboard'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/tools'
    | '/agents/$agentId/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  FilesRoute: typeof FilesRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  SkillsCreateRoute: typeof SkillsCreateRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/create': {
      id: '/skills/create'
      path: '/skills/create'
      fullPath: '/skills/create'
      preLoaderRoute: typeof SkillsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/voice': {
      id: '/agents/$agentId/voice'
      path: '/voice'
      fullPath: '/agents/$agentId/voice'
      preLoaderRoute: typeof AgentsAgentIdVoiceRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/tools': {
      id: '/agents/$agentId/tools'
      path: '/tools'
      fullPath: '/agents/$agentId/tools'
      preLoaderRoute: typeof AgentsAgentIdToolsRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/settings': {
      id: '/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/agents/$agentId/settings'
      preLoaderRoute: typeof AgentsAgentIdSettingsRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/memory': {
      id: '/agents/$agentId/memory'
      path: '/memory'
      fullPath: '/agents/$agentId/memory'
      preLoaderRoute: typeof AgentsAgentIdMemoryRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/dashboard': {
      id: '/agents/$agentId/dashboard'
      path: '/dashboard'
      fullPath: '/agents/$agentId/dashboard'
      preLoaderRoute: typeof AgentsAgentIdDashboardRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/chat': {
      id: '/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AgentsAgentIdChatRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdChatRoute: typeof AgentsAgentIdChatRoute
  AgentsAgentIdDashboardRoute: typeof AgentsAgentIdDashboardRoute
  AgentsAgentIdMemoryRoute: typeof AgentsAgentIdMemoryRoute
  AgentsAgentIdSettingsRoute: typeof AgentsAgentIdSettingsRoute
  AgentsAgentIdToolsRoute: typeof AgentsAgentIdToolsRoute
  AgentsAgentIdVoiceRoute: typeof AgentsAgentIdVoiceRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdChatRoute: AgentsAgentIdChatRoute,
  AgentsAgentIdDashboardRoute: AgentsAgentIdDashboardRoute,
  AgentsAgentIdMemoryRoute: AgentsAgentIdMemoryRoute,
  AgentsAgentIdSettingsRoute: AgentsAgentIdSettingsRoute,
  AgentsAgentIdToolsRoute: AgentsAgentIdToolsRoute,
  AgentsAgentIdVoiceRoute: AgentsAgentIdVoiceRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  FilesRoute: FilesRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  SkillsCreateRoute: SkillsCreateRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
